# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lab5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lab5
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'FBSDKShareKit'
end
